task/dcse: base
model_checkpoint: base
effective_batch_size: 512

task/dcse/dataset: fineweb
task/dcse/encoder/sem: h2, flat
task.dcse.delta_ent: 0.5, 1.0
task.dcse.teacher.model_name: SONAR

compile: false
max_steps: 30000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dcse/ent

