batch_size: 64
lr: 5e-5
lr_warmup_steps: 2000

encoder:
  model_name: FacebookAI/roberta-large
  train_backbone: true
  latent_length: 1
  latent_dim: 1024
  mlp_proj: true
  sem: 
    _target_: model.encoder.SEMHead
    L: 512
    V: 16
    temp: 0.75
    
dataset:
  name: fineweb
  val_size: 16384
  seed: 42

adjacent_positives: true
min_span_length: 64
max_span_length: 160
num_anchors: 2
num_positives: 2
loss_temp: 0.05
sem_noise: 0.05

name: base/declutr
