task/dlc_ar: baseline
model_checkpoint: base
effective_batch_size: 1024
task.dlc_ar.batch_size: 32

max_steps: 20000

limit_val_batches: 4
val_check_interval: 256

compile: true
sweep_id: dlc_ar/baseline

