task/dlc_ar: declutr
model_checkpoint: base

effective_batch_size: 512

task.dlc_ar.pretrained_declutr_id: 5cd19sua
task.dlc_ar.context_length: 112, 0

max_steps: 20000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dlc_ar/declutr

