task/dlc_ar: base
model_checkpoint: base
effective_batch_size: 1024

task.dlc_ar.pretrained_declutr_id: 5fpx7w1a
task.dlc_ar.context_length: 240, 0

max_steps: 20000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dlc_ar/declutr

