batch_size: 64
lr: 2e-5
lr_warmup_steps: 2000

encoder:
  model_name: FacebookAI/roberta-large
  train_backbone: true
  latent_length: 1
  latent_dim: 1024
  mlp_proj: false

dataset:
  name: fineweb
  val_size: 16384
  seed: 42

min_span_length: 32
max_span_length: 384
loss_temp: 0.05
sem_noise: 0.0

mteb_tasks:
  - STSBenchmark
  - Banking77Classification.v2
  - ArXivHierarchicalClusteringS2S
  - SciFact

name: simcse/cont
