batch_size: 64
lr: 1e-4
lr_warmup_steps: 1500
val_size: 16384
temp: 0.01
delta_ent: 1.0
reg_warmup_steps: 10000
ce_loss: True
sem_reset_schedule: [1, 20000, 5]
sem_reset_threshold: 1e-4
delta_margin: 0.5
reg_type: ent
sem_reset: false

name: base_dcse

teacher:
  model_name: nvidia/llama-embed-nemotron-8b #SONAR #Qwen/Qwen3-Embedding-0.6B 
  prompt: null
  
encoder:
  model_name: microsoft/deberta-v3-large

defaults:
  - encoder/sem: h2
  - encoder/dino_head: null
  - dataset: fineweb_long
