batch_size: 64
lr: 1e-5
lr_warmup_steps: 1500
val_size: 16384
temp: 0.01
delta_ent: 0.0
delta_ent_warmup_steps: 0

name: base_dcse

teacher:
  model_name: nvidia/llama-embed-nemotron-8b #SONAR #Qwen/Qwen3-Embedding-0.6B 
  prompt: null
  #prompt: "Represent the text with high-level features. This can include semantic information, type of text, intent, style. Text: "
  
encoder:
  model_name: microsoft/deberta-v3-large

defaults:
  - encoder/sem: flat
  - dataset: fineweb
