lr: 1e-4
batch_size: 32
decoder:
  name: gpt2-xl # 1.5B params
  lora_cfg: 
    r: 128
    lora_alpha: 32
    target_modules: ["c_attn", "c_proj"]
    lora_dropout: 0.1
    bias: "none"

max_generation_length: 150
dataset:
  path: data/

val_size: 1024