batch_size: 64
lr: 5e-5
lr_warmup_steps: 2000
max_length: 256
dataset_seed: 42
num_prototypes: 65536
head_nlayers: 3
student_temp: 0.1
teacher_temp: 0.04
center_momentum: 0.9
teacher_momentum: 0.996

encoder:
  model_name: FacebookAI/roberta-large
  train_backbone: true
  latent_length: 1
  latent_dim: 1024
  mlp_proj: false

declutr_dataset:
  name: fineweb
  val_size: 16384
  seed: 42

declutr_min_span_length: 64
declutr_max_span_length: 256
