batch_size: 64
lr: 2e-5
lr_warmup_steps: 2000
max_length: 256
dataset_seed: 42
dino_on_sem: true
mteb_tasks:
  - STSBenchmark
  - Banking77Classification.v2
  - ArXivHierarchicalClusteringS2S
  - SciFact
student_temp: 0.1
teacher_temp: 0.04
center_momentum: 0.9
teacher_momentum: 0.996
sem_noise: 0.00
declutr_only: true

encoder:
  model_name: FacebookAI/roberta-large
  train_backbone: true
  latent_length: 1
  no_out_proj: true
  sem:
    _target_: model.encoder.SEMHead
    L: 2048
    V: 16
    temp: 0.5

declutr_dataset:
  name: fineweb
  val_size: 16384
  seed: 42

declutr_min_span_length: 64
declutr_max_span_length: 256

name: dino_mixture/sem
