task/dlc_ddpm: ae
model_checkpoint: base

task.dlc_ddpm.pretrained_ae_id: 3h16x36n, vd8vtsfz
task.dlc_ddpm.normalize_latent: true, false
task.dlc_ddpm.noise_delta: 0.0, 0.2

max_steps: 20000

limit_val_batches: 4
val_check_interval: 512

sweep_id: dlc_ddpm/ae

