task/dlc_ddpm: declutr
model_checkpoint: base

task.dlc_ddpm.pretrained_declutr_id: v6jqgrwj
task.dlc_ddpm.normalize_latent: true
task.dlc_ddpm.use_ema: true
task.dlc_ddpm.noise_delta: 0.3

task.dlc_ddpm.context_length: 112, 0

max_steps: 20000

limit_val_batches: 4
val_check_interval: 512
strategy: ddp_find_unused_parameters_true

sweep_id: dlc_ddpm/declutr

