task/declutr: base
model_checkpoint: base
task.declutr.batch_size: 32

task.declutr.encoder.model_name: FacebookAI/roberta-large-mnli
task.declutr.sem_noise: 0.05

task.declutr.min_span_length: 100
task.declutr.max_span_length: 128

max_steps: 20000

limit_val_batches: 4
val_check_interval: 256

sweep_id: declutr/context

