lr: 2e-4
lr_warmup_steps: 2000
batch_size: 32
decoder:
  name: gpt2-medium # 1.5B params
  cross_attention: false
  attn_implem: sdpa

eval_gen_ppl: true

pretrained_ae_id: zzgjp12e
#pretrained_declutr_id: bll8h3yb
DLC_dropout: 0.0

prefix_length: null
suffix_length: null
context_length: null

name: dlc_ar/ae