lr: 1e-4
lr_warmup_steps: 500
batch_size: 32
decoder:
  name: gpt2-medium # 1.5B params
  cross_attention: false
  attn_implem: sdpa

dataset: fineweb
eval_gen_ppl: true
pretrained_ae_id: 4szrb171
DLC_dropout: 0.0

prefix_length: null
suffix_length: null
context_length: null
encoder_mode: null 

name: dlc_ar