lr: 2e-4
lr_warmup_steps: 1000
batch_size: 32
decoder:
  name: gpt2-medium # 1.5B params
  cross_attention: false
  attn_implem: sdpa

dataset: fineweb
eval_gen_ppl: true
pretrained_ae_id: 7x22772a
DLC_dropout: 0.0

name: ae_base