batch_size: 32
lr: 1e-4
lr_warmup: true
val_size: 16384
sub_p: 0.3
delta_ent: 0.0
delta_ent_warmup: False

encoder:
  name: SONAR 
  sem:
    _target_: model.encoder.HSEMHead
    L: 32
    V: 48
    D: 2
    dirichlet_eta: 0.00
    temp: 0.5

decoder:
  name: gpt2-large # 1.5B params
  prompt_generator_cfg:
    n_layers: 6
    n_heads: 12
    k: 8

name: sonar_sem

defaults:
  - dataset: wiki
