batch_size: 32
lr: 1e-4
max_generation_length: 150
val_size: 16384
z_noise_type: none

encoder:
  _target_: model.encoder.STEncoder
  name: SONAR 
  normalize: false
  train: true
  sem_cfg:
    L: 32
    V: 2048
    temp: 0.5
  dropout_p: 0.3

decoder:
  name: gpt2-large # 1.5B params
  prompt_generator_cfg:
    n_layers: 6
    n_heads: 12
    k: 8
  train: true

name: sonar_sem

defaults:
  - dataset: wiki
