lr: 1e-4
lr_warmup_steps: 1500
batch_size: 64
pretrained_ae_id: tvg79519
conditional: True
cond_split_bounds: null
cond_suffix_len: 32
seq_len: 64
dropout_p: 0.3

decoder:
  name: gpt2 # 0.7B params

name: dlclm