lr: 2e-4
lr_warmup_steps: 2000
batch_size: 64
val_batch_size: 32

dit:
  name: kuleshov-group/mdlm-owt
  sampling_steps: 512
  sampling_mode: remdm-cap  # mdlm, remdm-cap, remdm-loop  
  nucleus_p: 0.9  
  sampling_eps: 1e-3 

ancestral: true
eval_gen_ppl: true
pretrained_ae_id: vbc8szze

name: dlc_md/ae