lr: 5e-4
lr_warmup_steps: 2000
batch_size: 128

decoder:
  name: gpt2-medium # 1.5B params
  cross_attention: false
  attn_implem: sdpa

model:
  n_layers: 12
  n_heads: 12
  n_embd: 768
  seq_len: 64
  dropout: 0.0
  cond_modulation: true

eval_gen_ppl: true

pretrained_ae_id: uw5t6rkg

prefix_length: null
suffix_length: null
context_length: null

use_ema: false
noise_delta: 0.3
loss: l2
sampling_timesteps: 50
train_schedule: cosine
diffusion_objective: pred_v
schedule_scale: 1.0
sampler: ddpm
normalize_latent: false

name: ddpm_base