lr: 5e-5
lr_warmup_steps: 2000
batch_size: 32

dataset:
  name: fineweb
  val_size: 16384
  seed: 42
  
decoder:
  name: gpt2-medium # 1.5B params
  cross_attention: false
  attn_implem: sdpa

eval_gen_ppl: true

prefix_length: 16
suffix_length: 64

soft_prompt_len: 0
use_ema: false
latent_noise: false
soft_thought_noise_cond: false
loss: l2
sampling_timesteps: 100
train_schedule: cosine
diffusion_objective: pred_v
schedule_scale: 1.0
sampler: ddpm
normalize_latent: false

name: ddpm_base