task/ae: qwen, dae_compressor, dae_long_context
model_checkpoint: base
task.ae.train_batch_size: 32
task.ae.val_batch_size: 32
accumulate_grad_batches: 8
precision: bf16-mixed
limit_val_batches: 4
val_check_interval: 256

task.ae.encoder.normalize: true, false

sweep_id: ae_clean
