task/ae: dae_og
model_checkpoint: base
task.ae.train_batch_size: 16
task.ae.val_batch_size: 64
accumulate_grad_batches: 16
task.ae.has_noising: True
task.ae.z_noise_alpha: 0.7, 0.9
task.ae.z_dropout_p: 0.4

sweep_id: dae_og
