task/ae: dae_compressor
model_checkpoint: base
task.ae.train_batch_size: 4
task.ae.val_batch_size: 32
accumulate_grad_batches: 16
task.ae.decoder.prompt_generator_cfg.k: 16

task.ae.encoder.normalize: False
task.ae.z_noise_type: fixed, none
task.ae.encoder.input_dropout: True, False

sweep_id: dae_compressor_v4
