task/dlclm: base_dcse
model_checkpoint: base
effective_batch_size: 1024
task.dlclm.batch_size: 32 
task.dlclm.lr: 1e-4
task.dlclm.lr_warmup_steps: 1500
precision: bf16-mixed

task.dlclm.pretrained_dcse_id : 8u3qej3w, hwdxt81m, h17egqdn, gbx67i2e, v99qgmdx, l0zm2726, 61wvm518

compile: true
max_steps: 15000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dlclm_dcse_h_deberta

