task/dlclm: base_dcse
model_checkpoint: base
effective_batch_size: 1024
task.dlclm.batch_size: 32 
task.dlclm.lr: 1e-4
task.dlclm.lr_warmup: true
precision: bf16-mixed

task.dlclm.pretrained_dcse_id : mn3iv9qr, 6hk9b548, lbz984t8, jq3nmnif, quc4egke, 9tglye7n, ez99gfb9, wkmoghux

compile: true
max_steps: 15000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dlclm_dcse_flat

