task/dcse: base
model_checkpoint: base
effective_batch_size: 512
precision: bf16-mixed

task.dcse.encoder.sem.temp: 0.1, 0.5
task/dcse/encoder/sem: h2, flat
task.dcse.temp:  0.01, 0.005
task.dcse.delta_ent_warmup_steps: 0, 10000 

compile: false
max_steps: 15000

limit_val_batches: 4
val_check_interval: 256

sweep_id: distill_cse_h_qwen

