task/dcse: base
model_checkpoint: base
effective_batch_size: 512
precision: bf16-mixed

task/dcse/dataset: fineweb
task.dcse.dataset.length_interval: [32, 96]
task.dcse.encoder.sem.temp: 0.5
task/dcse/encoder/sem: h1, h2, flat
task.dcse.temp:  0.01
task.dcse.delta_ent: 0.0, 0.5
task.dcse.delta_ent_warmup_steps: 5000
task.dcse.teacher.model_name: Qwen/Qwen3-Embedding-0.6B, SONAR

compile: false
max_steps: 15000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dcse_fw_0

