task/dcse: h3
model_checkpoint: base
effective_batch_size: 512
task.dcse.batch_size: 32, 64
task.dcse.lr: 1e-5
task.dcse.lr_warmup_steps: 1000
precision: bf16-mixed

task.dcse.encoder.sem.temp: 0.25
task.dcse.encoder.model_name: microsoft/deberta-v3-large 
task.dcse.temp: 0.05, 0.005

compile: true
max_steps: 15000

limit_val_batches: 4
val_check_interval: 256

sweep_id: distill_cse_h_deberta_stab

