task/dlclm: base_dcse
model_checkpoint: base
effective_batch_size: 1024
task.dlclm.batch_size: 32 
task.dlclm.lr: 1e-4
task.dlclm.lr_warmup_steps: 1500
precision: bf16-mixed

task.dlclm.pretrained_dcse_id : 4tim1wlm, n8ok3xyo, c2n31n72, 2w3w8893, wsb9mw5f, sc1knmkb, uak0afbx, wb4t4jpm, 2mvtgdrz, t2e3u19f, glkrjt13, 1an6d78d, hw41ddm5, tc78mop4, 53811n8s, nbu4aeib

compile: false
max_steps: 10000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dlclm_dcse_h_qwen_0

