task/diffusion: base
model_checkpoint: base
effective_batch_size: 512
task.diffusion.batch_size: 16
task.diffusion.pretrained_ae_id: u10rszru, u1sdwz0y # sonar_frozen, qwen_dae
precision: bf16-mixed
limit_val_batches: 8
val_check_interval: 256

sweep_id: diffusion_v1

