task/diffusion: base
model_checkpoint: base
task.diffusion.batch_size: 128
accumulate_grad_batches: 2
precision: bf16-mixed
limit_val_batches: 4
val_check_interval: 256
task.diffusion.pretrained_ae_id: r08t35ja, qrdraeyp
task.diffusion.diffuse_prenorm: True
task.diffusion.normalize_latent: False

sweep_id: diffusion_nonorm
