task/dlclm: base
model_checkpoint: base
effective_batch_size: 1024
task.dlclm.batch_size: 32
task.dlclm.lr: 1e-5
task.dlclm.pretrained_ae_id: zj9quov2, 4dp80ubw, uixhbbuo, 9fb0pp6x, dl2fh5wd
precision: bf16-mixed
limit_val_batches: 8
val_check_interval: 256

sweep_id: dlclm_v2

