task/dlclm: base
model_checkpoint: base
effective_batch_size: 1024
task.dlclm.batch_size: 32
task.dlclm.lr: 1e-5
task.dlclm.pretrained_ae_id: 13dfit14, blettf7k, tv782ad3, ces0e8py, 3xcpjten, zvbix89o
precision: bf16-mixed
limit_val_batches: 8
val_check_interval: 256
compile: true

sweep_id: dlclm_clean

