task/dlclm: ae
model_checkpoint: base
effective_batch_size: 1024

task.dlclm.lr: 5e-5
task.dlclm.pretrained_ae_id: mteehhfy, st6xuq0i, wwtq4qxw, 9z0fvmm5
task.dlclm.decoder.name: gpt2
task.dlclm.cond_suffix_len: 32
task.dlclm.seq_len: 64

compile: false
max_steps: 30000

limit_val_batches: 4
val_check_interval: 256

sweep_id: dlclm_ae_v5