task/ae: sem/sonar_h1, sem/sonar_h2, sem/sonar_h3
model_checkpoint: base
effective_batch_size: 1024
task.ae.batch_size: 32 
task.ae.lr: 1e-4
precision: bf16-mixed

task.ae.encoder.train: true
task.ae.decoder.train: true
task.ae.encoder.hsem_cfg.temp: 0.5

compile: true
max_epochs: 2

limit_val_batches: 8
val_check_interval: 256

sweep_id: h_sem_vae

