task/ae: dae, dae_compressor
model_checkpoint: base
task.ae.train_batch_size: 16
task.ae.val_batch_size: 64
accumulate_grad_batches: 16
task.ae.decoder.prompt_generator_cfg.k: 16
task.ae.encoder.normalize: False

sweep_id: no_norm
