task/ae: sem/sonar
model_checkpoint: base
effective_batch_size: 1024
task.ae.batch_size: 32 
task.ae.lr: 1e-4
task.ae.lr_warmup: true
precision: bf16-mixed

task.ae.encoder.sem.temp: 1.0
task.ae.encoder.sem.L: 64, 128

compile: true
max_steps: 30000

limit_val_batches: 4
val_check_interval: 256

sweep_id: sem_L

