task/ae: sem/sonar
model_checkpoint: base
effective_batch_size: 1024
task.ae.lr: 1e-5, 1e-6
task.ae.batch_size: 32 
precision: bf16-mixed
task.ae.encoder.train: false
task.ae.decoder.train: true
compile: false

limit_val_batches: 8
val_check_interval: 256

sweep_id: sem_ae_lr_bs

