task/ae: sem/sonar
model_checkpoint: base
effective_batch_size: 1024
task.ae.batch_size: 32 
task.ae.lr: 1e-4, 5e-5, 1e-5 
precision: bf16-mixed

task.ae.encoder.train: true
task.ae.decoder.train: true
task.ae.encoder.sem_cfg.temp: 0.5
task.ae.encoder.sem_cfg.V: 2048
task.ae.encoder.sem_cfg.L: 32
task.ae.lr_schedule: True

compile: false
max_epochs: 2

limit_val_batches: 8
val_check_interval: 256

sweep_id: sem_schedule_test

