task/ae: st5
model_checkpoint: base
task.ae.train_batch_size: 16
task.ae.val_batch_size: 64
accumulate_grad_batches: 16
task.ae.decoder.prompt_generator_cfg.k: 16
task.ae.z_noise_type: schedule
task.ae.z_noise_alpha: 0.95, 0.7
task.ae.z_dropout_p: 0.05, 0.2


sweep_id: st5_noise_v2
