task/ae: qwen_norm, qwen_norm_drop, dae_long_context, dae_pool_norm_nodrop
model_checkpoint: base
task.ae.train_batch_size: 16
task.ae.val_batch_size: 64
accumulate_grad_batches: 16
precision: bf16-mixed
limit_val_batches: 4
val_check_interval: 256

sweep_id: wiki_v0
