defaults:
  - train_config
  - _self_
  - logger: base
  - hydra: base
  - task/ae: null
  - task/diffusion: null
  - model_checkpoint: base
 
seed: 42
log_dir: /network/scratch/l/leo.gagnon/sentence_diffusion/logs
max_epochs: 200
accumulate_grad_batches: 8
val_check_interval: 250
name: diffusion_base

task:
  diffusion:
    model:     
      n_layers: 8
      n_heads: 8
      n_embd: 512

    batch_size: 64
    val_split: 0.1
    lr: 1e-4
    ae_id: gfdrgnxn

    loss: l2
    sampling_timesteps: 50
    train_schedule: cosine
    diffusion_objective: pred_v
    sampler: ddpm
    normalize_latent: True