defaults:
  - train_config
  - _self_
  - logger: base
  - hydra: base
  - task/ae: null
  - task/diffusion: null
  - task/finetune: null
  - model_checkpoint: null
  - early_stopping: null
  - hydra/sweeper/params : null
  - override hydra/launcher : base
  
seed: 42
log_dir: /network/scratch/l/leo.gagnon/sentence_diffusion/logs
max_epochs: 200
accumulate_grad_batches: 16
val_check_interval: 128
sweep_id: null