defaults:
  - train_config
  - _self_
  - logger: base
  - hydra: base
  - task/ae: null
  - task/dcse: null
  - task/dlclm: null
  - model_checkpoint: null
  - early_stopping: null
  - hydra/sweeper/params : null
  - override hydra/launcher : fir
  
seed: 1337
log_dir: null
max_steps: 15000
effective_batch_size: 1024
val_check_interval: 128
sweep_id: null
precision: bf16-mixed
limit_val_batches: 4
strategy: ddp #auto
compile: false
gradient_clip_val: 1.0
num_devices: null