task/ae: base
model_checkpoint: base
effective_batch_size: 1024
task.ae.batch_size: 64

task/ae/encoder/sem: flat
task.ae.prefix_length: 16
task.ae.suffix_length: 64
task.ae.sem_noise: 0.3
task.ae.encoder.sem.hard_renorm: false
task.ae.denoising: true
task.ae.encoder.sem.baseline: true

max_steps: 20000

limit_val_batches: 4
val_check_interval: 256

sweep_id: ae/baseline_0

