task/ae: base
model_checkpoint: base
effective_batch_size: 1024
task.ae.batch_size: 64

task.ae.prefix_length: 16
task.ae.suffix_length: 64
task.ae.context_length: 112
task.ae.encoder_mode: context
task.ae.encoder.sem.L: 16, 512
task.ae.denoising: false
task.ae.encoder.train_backbone: true

max_steps: 20000

limit_val_batches: 4
val_check_interval: 256

sweep_id: ae/context_0

