task/ae: base
model_checkpoint: base
effective_batch_size: 1024

task/ae/dataset: fineweb
task/ae/encoder/sem: flat
task.ae.encoder.sem.V: 32, 512
compile: false
max_steps: 30000

limit_val_batches: 4
val_check_interval: 256

sweep_id: ae/flat_V

