task/ae: base
model_checkpoint: base
effective_batch_size: 1024
task.ae.batch_size: 64
task.ae.lr_warmup_steps: 1000
task.ae.lr: 2e-5
task/ae/dataset: fineweb
task.ae.dataset.length_interval: [64,64]
task/ae/encoder/sem: flat
task.ae.encoder.sem.V: 8, 128
task.ae.encoder.sem.L: 8, 128
task.ae.sem_noise: 2.0
task.ae.encoder.sem.per_simpex_ln: true
task.ae.delta_margin: 0.5
task.ae.delta_ent: 1.0
task.ae.reg_warmup_steps: 12000
task.ae.sem_reset_threshold: 1e-4
task.ae.sem_reset_schedule: [1000, 10000, 500]

task.ae.sem_reset: false
task.ae.reg_type: none

compile: false
max_steps: 15000

limit_val_batches: 4
val_check_interval: 256

sweep_id: ae/sweep4

