defaults:
  - submitit_slurm

mem_gb: 32
gres: gpu:a100l:4
tasks_per_node: 4
array_parallelism: 32
nodes: 1 
cpus_per_task: 2
timeout_min: 360 # 6 hours
partition: long
additional_parameters:
  no-requeue: true

setup:
  - "export NCCL_DEBUG=INFO"
  - "source ~/sentence_diffusion/venv/bin/activate"