defaults:
  - submitit_slurm

mem_gb: 64
gres: gpu:l40s:1
tasks_per_node: 1
array_parallelism: 32
cpus_per_task: 4
timeout_min: 960 # 16 hours
partition: long

setup:
  - "source ~/sentence_diffusion/venv/bin/activate"