defaults:
  - submitit_slurm

mem_gb: 32
gres: gpu:l40s:1
tasks_per_node: 1
array_parallelism: 32
cpus_per_task: 1
timeout_min: 480 # 8 hours
partition: long

setup:
  - "source ~/sentence_diffusion/venv/bin/activate"