defaults:
  - submitit_slurm

mem_gb: 256
gpus_per_node: 4
array_parallelism: 32
nodes: 1 
tasks_per_node: 4
cpus_per_task: 4
timeout_min: 360 #719 # 360
account: aip-glaj
additional_parameters:
  no-requeue: true

setup:
  - "export NCCL_DEBUG=INFO"
  - "source ~/sentence_diffusion/venv/bin/activate"