model:     
  n_layers: 8
  n_heads: 8
  n_embd: 512

batch_size: 128
val_split: 0.1
lr: 1e-4
ae_id: jvktv590

loss: l2
sampling_timesteps: 50
train_schedule: cosine
diffusion_objective: pred_v
sampler: ddpm
normalize_latent: True