model:     
  n_layers: 16
  n_heads: 8
  n_embd: 768

batch_size: 128
lr: 1e-4
pretrained_ae_id: 983t3fhv

loss: l2
sampling_timesteps: 50
train_schedule: cosine
diffusion_objective: pred_v
sampler: ddpm
normalize_latent: True