task/dlc_ddpm: ae
model_checkpoint: base

task.dlc_ddpm.pretrained_ae_id: uw5t6rkg, p2d8csdo
task.dlc_ddpm.prompt_generator_noise: true, false

max_steps: 20000

limit_val_batches: 4
val_check_interval: 512
strategy: ddp_find_unused_parameters_true

sweep_id: dlc_ddpm/ae

