task/dlc_ddpm: declutr
model_checkpoint: base

task.dlc_ddpm.suffix_length: 256, 64
effective_batch_size: 512

max_steps: 20000

limit_val_batches: 8
val_check_interval: 512
strategy: ddp_find_unused_parameters_true

sweep_id: dlc_ddpm/declutr

