task/dlc_ddpm: jina_cluster
model_checkpoint: base

max_steps: 20000

task.dlc_ddpm.context_length: 64
task.dlc_ddpm.suffix_length: 64, 256
effective_batch_size: 512

limit_val_batches: 8
val_check_interval: 512

strategy: ddp_find_unused_parameters_true

sweep_id: dlc_ddpm/jina_1

