task/dlc_ddpm: ul_rob
model_checkpoint: base

task.dlc_ddpm.prior_logsnr_max: 3.0, 5.0
task.dlc_ddpm.diffusion_beta: 5.0

max_steps: 20000

effective_batch_size: 512

limit_val_batches: 8
val_check_interval: 512

strategy: ddp_find_unused_parameters_true

sweep_id: dlc_ddpm/ul_rob

