batch_size: 64
lr: 1e-4
lr_warmup_steps: 1000
val_size: 16384
sub_p: 0.3
delta_ent: 1.0
delta_margin: 0.5
reg_warmup_steps: 10000
sem_reset_schedule: [1000, 10000, 500]
sem_reset_threshold: 1e-4
reg_type: ent
sem_reset: false
sem_noise: 0.3
sem_noise_warmup_steps: 10000

encoder:
  model_name: microsoft/deberta-v3-large 

decoder:
  name: gpt2 # 1.5B params
  prompt_generator_cfg:
    n_layers: 4
    n_heads: 12
    k: 8

name: base_ae

defaults:
  - encoder/sem: flat
  - dataset: fineweb
