batch_size: 64
lr: 2e-4
lr_warmup_steps: 500
sem_noise: 0.3
sem_noise_warmup_steps: 0
prefix_length: 16
suffix_length: 64
context_length: 112
denoising: true
encoder_mode: context
sem_reset_config:
  enabled: false
  simplex_mode: false
  threshold: 1e-3
  start: 5000
  end: 15000
  interval: 5000

dataset:
  name: fineweb
  val_size: 16384
  seed: 42

encoder:
  model_name: SONAR
  train_backbone: true
  latent_length: 32
  sem: 
    _target_: model.encoder.SEMHead
    L: 512
    V: 16
    temp: 1.0

decoder:
  name: gpt2-large # 1.5B params
  cross_attention: True
  attn_implem: sdpa

name: base_ae
