batch_size: 64
lr: 5e-4
lr_warmup_steps: 1000
sem_noise: 0.0
sem_noise_warmup_steps: 0
prefix_length: 16
suffix_length: 112
context_length: 0
denoising: true
encoder_mode: suffix

dataset:
  name: fineweb
  val_size: 16384
  seed: 42

encoder:
  model_name: SONAR
  train_backbone: true
  latent_length: 32

decoder:
  name: gpt2-medium # 1.5B params
  cross_attention: True
  attn_implem: sdpa

name: ae_continuous
