train_batch_size: 16
val_batch_size: 64
lr: 1e-4
max_generation_length: 100
val_size: 512
z_noise_alpha: 0.8
z_dropout_p: 0.2
has_noising: True

encoder:
  _target_: model.encoder.DAEEncoder
  name: thesephist/contra-bottleneck-t5-large-wikipedia
  normalize: True
  token_dropout_p: 0.3
  compressor_cfg:
    n_layers: 1
    n_heads: 8
    dim: 6144
  lora_cfg: 
    r: 128
    lora_alpha: 32
    target_modules: ["q", "v", "o", "wi", "wo"]
    lora_dropout: 0.1
    bias: "none"

decoder:
  name: gpt2-large # 1.5B params
  prompt_generator_cfg:
    n_layers: 6
    n_heads: 12
    input_dim: null # to be set dynamically
    k: 16
  lora_cfg: 
    r: 128
    lora_alpha: 32
    target_modules: ["c_attn", "mlp.c_fc", "mlp.c_proj"]
    lora_dropout: 0.1
    bias: "none"
    
dataset:
  path: data/

name: dae_compressor

