train_batch_size: 16
val_batch_size: 32
lr: 1e-4
max_generation_length: 128
val_size: 16384
z_noise_type: fixed
z_noise_alpha: 0.9
z_dropout_p: 0.0

encoder:
  _target_: model.encoder.DAEEncoder
  name: thesephist/contra-bottleneck-t5-xl-wikipedia
  normalize: True
  dropout_p: 0.3
  input_dropout: True
  out_dim: 2048
  lora_cfg: 
    r: 128
    lora_alpha: 32
    target_modules: ["q", "v", "o", "wi", "wo"]
    lora_dropout: 0.1
    bias: "none"

decoder:
  name: gpt2-large # 1.5B params
  prompt_generator_cfg:
    n_layers: 6
    n_heads: 12
    k: 16
    noise_conditioning: False
  lora_cfg: 
    r: 128
    lora_alpha: 32
    target_modules: ["c_attn", "mlp.c_fc", "mlp.c_proj"]
    lora_dropout: 0.1
    bias: "none"  

name: dae_pool

defaults:
  - dataset: wiki
