batch_size: 64
lr: 1e-4
lr_warmup_steps: 1000
val_size: 16384
sub_p: 0.3
delta_ent: 1.0
delta_margin: 0.5
reg_warmup_steps: 10000
sem_reset_schedule: [5000, 10000, 1000]
sem_reset_threshold: 1e-4
reg_type: ent
sem_reset: false

encoder:
  model_name: microsoft/deberta-v3-large 

decoder:
  name: gpt2-large # 1.5B params
  prompt_generator_cfg:
    n_layers: 4
    n_heads: 12
    k: 8

name: base_ae

defaults:
  - encoder/sem: h2
  - dataset: fineweb_long
