train_batch_size: 32
val_batch_size: 128
lr: 1e-4
input_sub_p: 0.0
kl_beta: 1e-6
max_generation_length: 150
val_size: 256

encoder:
  name: bert-large-uncased # 336M params
  k: 16
  compressor_cfg:
    n_layers: 4
    n_heads: 8
    act_masking_p: 0.0
    feat_masking_p: 0.0
    act_delta: 0.0
  lora_cfg: 
    r: 128
    lora_alpha: 32
    target_modules: ["query", "value", "dense"]
    lora_dropout: 0.1
    bias: "none"

pretrained_decoder_id: oj4gfj5q #7s8obxmf
    
dataset:
  path: data/

