train_batch_size: 32
val_batch_size: 32
lr: 1e-4
max_generation_length: 128
val_size: 16384
z_noise_type: fixed
z_noise_alpha: 0.95
z_dropout_p: 0.0

encoder:
  _target_: model.encoder.STEncoder
  name: SONAR # 1.5B params
  normalize: false

decoder:
  name: gpt2-large # 1.5B params
  prompt_generator_cfg:
    n_layers: 6
    n_heads: 12
    k: 8
  lora_cfg: 
    r: 64
    lora_alpha: 16
    target_modules: ["c_attn", "mlp.c_fc", "mlp.c_proj"]
    lora_dropout: 0.1
    bias: "none"

name: qwen

defaults:
  - dataset: wiki
