batch_size: 2
lr: 1e-4
lr_warmup_steps: 1000
val_size: 16384
delta_ent: 0.0
reg_warmup_steps: 10000
sem_noise: 0.3
sem_noise_warmup_steps: 10000
prefix_length: 16
suffix_length: 64
#context_length: 96
denoising: false
encoder_mode: suffix

encoder:
  model_name: SONAR
  latent_length: 16

decoder:
  name: gpt2-large # 1.5B params
  cross_attention: True

dataset:
  _target_: data.datasets.FineWebDataset

name: base_ae

defaults:
  - encoder/sem: flat
