task/dlc_md: declutr
model_checkpoint: base

effective_batch_size: 512

task.dlc_md.pretrained_declutr_id: bqjy99qs
task.dlc_md.context_length: 112, 0
task.dlc_md.prefix_length: 16
task.dlc_md.suffix_length: 64
task.dlc_md.ancestral: True, False

max_steps: 20000

limit_val_batches: 4
val_check_interval: 512

sweep_id: dlc_md/declutr_5

